### ISSUE TITLE
Key command triggered when entering branch name

### ISSUE THREAD

**Issue by aparlato** [stamen/maperture#105]
https://github.com/stamen/maperture/pull/100 introduced a key command to hide the UI (`v`). Unfortunately, we made the oversight of allowing this key command to be triggered by a key press even when writing in an input.

We should see if it's easy to check for when someone is focused on an input, but otherwise, the shortest road to fixing this bug is to change the hot key.

**Comment by almccon** [comment]
Ahh yes, thanks, this bit me once yesterday but I forgot to report it!
