### ISSUE TITLE
feature request: ability to hide both menus 

### ISSUE THREAD

**Issue by kkowalsky** [stamen/maperture#109]
When map panes  > 3, it becomes exponentially harder to see as much map real estate as i'd like because the sizing on the map selector doesn't shrink and there's no option to hide that box. Being able to just hide that menu in the bottom right corner for screenshots or being able to see small multiples while working would be an awesome lifestyle improvement.

**Comment by ebrelsford** [comment]
@kkowalsky Thanks for this! Maybe I'm not understanding but there are a few features that I think cover this use case.

First, in the latest version you can hide all of the UI:

![image](https://user-images.githubusercontent.com/375002/193967332-638e7901-208d-4039-88ed-779385710de8.png)

![image](https://user-images.githubusercontent.com/375002/193967453-29989ae5-ff42-4b55-a95b-74acc00b2490.png)

Second, if all you're looking for is a screenshot, this button removes all of the UI and does that for you:

![image](https://user-images.githubusercontent.com/375002/193968542-65bacbdf-acbd-4fe8-9557-023ca7e7fc68.png)

Is there something else we could do to get at what you're trying to do?

**Comment by aparlato** [comment]
@kkowalsky yes! This should be in today's port: https://github.com/stamen/aws-map-styles/pull/265
