### ISSUE TITLE
Stop spamming browser history

### ISSUE THREAD

**Issue by aparlato** [stamen/maperture#124]
Right now, we [change the URL hash by setting `window.location.hash`](https://github.com/stamen/maperture/blob/main/src/query.js#L123). This creates a new history entry on every change in Maperture _including_ map location changes (although it's throttled). This means browser history gets pretty spammed:
![image](https://user-images.githubusercontent.com/15698320/199258817-5c7b0a35-1498-42c7-b87d-c15b79db3719.png)

We should consider a different method of updating the hash using something like `window.location.replace`.

Would we want to maintain browser history for certain changes and not others? We might also just use `window.location.replace` for location changes and maintain our current set up for other changes.

**Comment by almccon** [comment]
Yeah, I run into this all the time, where I'll follow a maperture link from a github issue and browse around the map a bit, and then try to go back to the issue and I discover I've panned around _a lot_ and it's a pain to get back to the previous page. I've been training myself to open maperture links in a new tab, but sometimes I forget.
