### ISSUE TITLE
Rethink how linking/unlinking locations of map panes works

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#125]
We've had a few questions and enhancement requests for the linking/unlinking locations functionality:
 * #121 
 * #122 

Let's use this issue as an opportunity to collect other feedback about this functionality and consider how it could be clearer and more useful.

**Comment by mulloverit** [comment]
@ebrelsford I'm going to close here since this ticket hasn't seen any action - please re-open if you'd like to make any additions here!
