### ISSUE TITLE
Copied image has uneven black border

### ISSUE THREAD

**Issue by kateler** [stamen/maperture#133]
When the `Copy image` button is pressed, the resulting image saved to my clipboard has a black border around it, which is thicker on the left and top than the right and bottom. 

This is inconvenient, because when sharing screenshots I need to manually crop out this border first (because I never want a border). 

Here's an example: 
![image](https://user-images.githubusercontent.com/764181/207941284-5b68dc8c-fa36-4f82-84df-7154b5bf2846.png)

**Comment by mulloverit** [comment]
* group agrees to remove border entirely
* follow-up issue: address attribution bar
