### ISSUE TITLE
Make it clear in the UI which map renderer is being used for each map pane

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#146]
Part of stamen/carto-tools#67.

A user should be able to determine which map renderer is in use for each map they're looking at.

Currently it isn't obvious to the user which map renderer is being used to display a map. This is a setting in the configuration file, but not everyone has access to that file and it's not very convenient to refer back to that file.

The only information the user sees right now is the name of the map style, as defined in the configuration file:

![image](https://user-images.githubusercontent.com/375002/213018690-43eb95ec-e619-47e9-b5c7-02e5c776cdbe.png)

We should make a way for users to optionally find out which renderer is in use.

### Acceptance criteria
 * Through the UI, user can determine which map renderer is being used to render each map pane

**Comment by kelsey-taylor** [comment]
i'm going to take a first pass at this and review with @ebrelsford later this week 🎨

**Comment by kelsey-taylor** [comment]
ideas for review posted over in https://github.com/stamen/maperture/issues/147#issuecomment-1400811484

**Comment by ebrelsford** [comment]
Closing in favor of #147--we'll handle the solution to both issues the same way.
