### ISSUE TITLE
Add a way to specify which map renderer to use for styles that could be rendered with mulitple renderers

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#147]
Part of stamen/carto-tools#67.

Related to #146.

Currently the only way to specify which map renderer a style should use is via the configuration file for a Maperture deployment. We should add a way to switch between renderers in the UI.

### Considerations
 * The UI for the map pane is pretty minimal at the moment, but there are other issues that could impact it:
   * #146 
   * #84
   * #79 
 * Currently the supported renderers that overlap in vector style formats are Mapbox GL JS and Maplibre, but we should stay open to other renderers that can accept similar styles
 * Other renderers can accept similar raster layers (Mapbox GL, Maplibre, Leaflet, and Openlayers all can). This is lower priority but we shouldn't close off the possibility of using these renderers interchangeably in that situation.

### Acceptance criteria
 * When it is possible to render a style with multiple renderers, a user can switch between those renderers in the UI
 * The chosen renderer should be saved in the URL parameters with the rest of the state of the application
 * Changes to the configuration file should be backwards compatible
 * The user should be able to do this with styles loaded via URL, too

**Comment by kelsey-taylor** [comment]
I've been noodling on these for a few days and here are the options I've come up with:

![image](https://user-images.githubusercontent.com/57634568/214123048-400e9723-89b2-4c14-91fa-41495dd1f342.png)

pros of either option:
- clearly see what render is in use in each pane
- clearly see if other renderers are/aren't available for each style
- renderer visible regardless of view type (swipe/mirror/phone/responsive)
- excluded from image copy (unless you want to include it, in which case you can screenshot manually)
- easy to switch renderers if the configuration for that map allows for it

cons:
- renderer not automatically included in image copy

Between the two, my preference is definitely for the dropdown, as it allows us to easily expand to additional renderers without taking up additional space in the UI. It does make the UI a little dropdown-heavy, but I don't think that's a big deal personally.

Would love thoughts/feedback/questions @ebrelsford @aparlato!

**Comment by ebrelsford** [comment]
This is similar to what I had in mind, thanks for sketching out the options! Definitely leaning toward the **dropdown** version for flexibility.

Do you think there's any need to move to a separate settings panel? Just imagining the (minimal) extra space this will take up when you have 4+ map panes...

**Comment by kelsey-taylor** [comment]
I was thinking the same thing @ebrelsford! I'm inclined to start with this and then minimize if we find that they panes are too crowded - what do you think?

**Comment by ebrelsford** [comment]
Works for me.

**Comment by kelsey-taylor** [comment]
Great! Let's proceed with the dropdown option then. Going to unassign myself here as this is ready for implementation.

**Comment by ebrelsford** [comment]
I'm still working on this (in #152) but @kelsey-taylor I'm wondering what you think about how this feels so far?

![image](https://user-images.githubusercontent.com/375002/215818960-d8353e79-587a-4e3d-bdda-ba5f60ae212f.png)

I'm tempted to make the renderer dropdown more explicit, say, "Rendered with <dropdown>".

**Comment by kelsey-taylor** [comment]
looking great so far! i'm definitely on board with adding a "rendered with" - maybe we could make that header a bit smaller than the style name. 

threw a couple quick options together - i think i prefer the second

<img width="712" alt="Screenshot 2023-01-31 at 11 30 15 AM" src="https://user-images.githubusercontent.com/57634568/215821363-0f2ad739-6692-4707-9390-6d16d270b76e.png">

**Comment by ebrelsford** [comment]
Yeah I think the second would be good, same page!
