### ISSUE TITLE
Deal with Maplibre/Mapbox logo and other CSS overlapping

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#150]
As mentioned in #148, it's very confusing that the Maplibre logo appears even when you're using only Mapbox GL for your maps:

![image](https://user-images.githubusercontent.com/375002/213748216-980c08c2-8db5-499b-9be7-7ace4a076d8e.png)

As I see it, this is happening because we bundle all of the CSS together and the Maplibre CSS is coming after the Mapbox CSS and overriding it.

We should:
 * [ ] Ensure the correct logo appears for a given map. Maybe it would be reasonable to hide the logos from the map but give credit in the map pane settings?
 * [ ] Look into whether other CSS will be impacted. It seems like the rest is probably fine but maybe as the projects diverge it will matter more?

**Comment by kelsey-taylor** [comment]
I've been thinking about this a lot in conjunction with #147 and #146 - I think removing the watermark altogether is the cleanest solution. You can't see it for all maps at once in swipe mode anyway, so I'm not sure it's providing much value at the moment. Will follow up in the other tickets about what solutions we can try to show the renderer in the UI instead

**Comment by ebrelsford** [comment]
Agreed, leaning that way too.

**Comment by aparlato** [comment]
> I think removing the watermark altogether is the cleanest solution

Just posting how to do this here if helpful since I just did it elsewhere in a private repo. Just need to add this into the CSS for `Map.svelte`
```
/* Remove Mapbox attribution */
  :global(.mapboxgl-control-container) {
    display: none;
  }
```
