### ISSUE TITLE
Autoprefix CSS

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#155]
As came up in #154, we should perhaps autoprefix our CSS to include browser-specific prefixes.

One option would be [postcss/autoprefixer](https://github.com/postcss/autoprefixer) with [egoist/rollup-plugin-postcss](https://github.com/egoist/rollup-plugin-postcss) to add it to the build process.

**Comment by mulloverit** [comment]
**User story**
Maperture is used pretty heavily internally for cartography. Adding prefixes to css helps with compatibility for browsers that require this. There are tools that exist to automatically do this, but we don't have them integrated yet. 

If a client were to open a link to Maperture in a browser that doesn't support this, they would have a bad experience. This work ensures a positive rendering and functionality experience of the tool we are sharing. 

**Acceptance criteria**
* Justification for why we chose to use one existing solution over another (there are several options out there)
* Implementation of that tool in Maperture
