### ISSUE TITLE
Add layer name to feature popup

### ISSUE THREAD

**Issue by RossThorn** [stamen/maperture#157]
## User story
Maperture is a commonly used tool for our cartography workflows; it is primarily used for creating stylesheets. Right now, the popup shows the source and the attribute for the specific feature of interest.

When working with layers in a stylesheet (especially in a build system that is segmented out) it would be helpful to know what layer a particular feature is in when clicking and seeing the popup. This is particularly useful when QAing a style, so if a bug or unexpected render is spotted, the user can easily find the corresponding layer (file) where the style rules are defined.

This improvement to the tool would speed up stylesheet development work and debugging.

## Acceptance criteria

- The user is able to see the correct layer in the popup that the feature is in.

The popup when clicking on a feature in the basemap lists the source for the feature. It would be nice if the popup also showed the layer that feature is being styled in. 

For example, the label for Maryland has the composite source of `place_label` but is in the `state-label` layer of the stylesheet. it would be helpful to see that

![image](https://user-images.githubusercontent.com/24381390/222496720-6225b4a2-82cc-4129-894d-ba216367ef9e.png)

**Comment by RossThorn** [comment]
My proposed US and AC!

## User story
The feature popup functionality in Maperture is great for getting on-the-fly information about the data in the tiles. Right now, the popup shows the source and the attribute for the specific feature of interest.

When working with layers in a stylesheet (especially in a build system that is segmented out) it would be helpful to know what layer a particular feature is in when clicking and seeing the popup. This is particularly useful when QAing a style, so if a bug or unexpected render is spotted, the user can easily find the corresponding layer (file) where the style rules are defined.

## Acceptance criteria

- The user is able to see the correct layer in the popup that the feature is in.

**Comment by mulloverit** [comment]
From grooming meeting, adding the business case:
- Maperture is a commonly used tool for our cartography workflows; it is primarily used for creating stylesheets
- This improvement to the tool would speed up stylesheet development work and debugging
Otherwise, looks good!
