### ISSUE TITLE
Maperture via link showing branch as custom URL

### ISSUE THREAD

**Issue by mizmay** [stamen/maperture#178]
When I click through to Maperture in a PR in the Toner repo, I get this:
![Screenshot 2023-05-26 at 11 20 33 AM](https://github.com/stamen/maperture/assets/3074691/6784b005-9e5f-4e35-84d8-69b6e7036cae)

The two panels are different (labels are smaller) but it's not clear what this comparison is.

What I'd expect to see are two panels clearly labeled, one as main and the other as the branch with the changes proposed in the PR.

**Comment by aparlato** [comment]
After investigation, I realized this was due to a syntax error in how we wrote our branch option in the downstream repo's config.

Closing this issue as resolved and fixing downstream.
