### ISSUE TITLE
Add labels in clipboard screenshots

### ISSUE THREAD

**Issue by aparlato** [stamen/maperture#182]
Right now screenshots exclude the UI to keep as much focus on the side by side maps as possible. However, with multiple maps, it's possible to get confused about which are which.

We might be able to pretty easily insert a thin label div at the top of each map panel (less obtrusive than the actual UI elements) and remove it post-screenshot to clipboard. This label can simply show the name of the map.

**Comment by ebrelsford** [comment]
Sounds reasonable to me.
