### ISSUE TITLE
Support other map engines

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#35]
Eventually we may want to support other map engines:
 * [OpenLayers](https://openlayers.org/)
 * [Leaflet](https://leafletjs.com/)
 * [deck.gl](https://deck.gl/)
 * [protomaps.js](https://github.com/protomaps/protomaps.js)

We shouldn't start work on any of these until there's a concrete need. @almccon are there any others you can think of we might realistically want to support? We'd love to think ahead a bit and consider what changes might need to happen to support as many of these as we can.

**Comment by mulloverit** [comment]
Not much benefit from keeping this list as an active issue since each engine will be a different lift. We do have a few options in already, so let's close here until there is a client need.
