### ISSUE TITLE
Add a way to minimize/hide the UI

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#45]
It could be nice to have a way to get rid of as much of the UI as you can while you're comparing map styles.

**Comment by almccon** [comment]
This feels related to #36, since the only time I really care about what the UI is doing is when I'm adjusting the browser window to take a series of screenshots, and I want to make sure the UI is as compressed as possible but still readable (since I want my screenshot to contain a record of which layer settings are active in each pane, and also to include the zoom/lat/lon/etc (and also what preset bookmark location/view I'm using)

**Comment by kateler** [comment]
I would also like a way to minimize the UI on top of the map when I'm not using it. The style selection boxes at the bottom in particular take up a lot of space.

**Comment by ebrelsford** [comment]
@aparlato Can we think through what this might look like? I think a button that toggles the UI (and maybe also a hotkey?) could suffice.

**Comment by aparlato** [comment]
Yea, I agree this could be something simple. Maybe just a separate button in the corner with an eye icon?
Visible UI:
![image](https://user-images.githubusercontent.com/15698320/188903268-c79257d0-608b-4456-8c2b-b7b7fd651f6c.png)
Invisible UI:
![image](https://user-images.githubusercontent.com/15698320/188903304-b3a2c5e4-6983-4381-ad07-ca807c15d263.png)

Could also have something more akin to a fullscreen mode where the top bar is fixed to the top and no longer floats and the style selection boxes are minimized except on hover:
![image](https://user-images.githubusercontent.com/15698320/188905649-4c564b16-c40c-4554-ba72-808a2b7de24e.png)
![image](https://user-images.githubusercontent.com/15698320/188906161-a649dc74-c9d7-44e9-937c-e826f274c2f3.png)

I'm open to either approach, but something closer to the first feels the simplest and most straight forward. If we go with the first, I think a hotkey of `v` for visible makes sense. If we go for something closer to the second, maybe `f` for fullscreen?

**Comment by ebrelsford** [comment]
I think the first is a good approach, but how would you feel about keeping the fullscreen icon and putting it in the top bar to make it more clearly associated with the UI? It would still hide all of the UI except for a button to show the UI.
