### ISSUE TITLE
Add a way to load individual tiles and style them

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#58]
Would be handy for situations where we are building tiles to debug the tile output.

One way this could work:

1. Drag-and-drop tile into one of the map panes
2. Dynamically switch the tile source to the given tile and style it based on the style you have loaded on that map pane

**Comment by mulloverit** [comment]
Sounds like a heavy lift for unknown payoff. @dnomadb has created something that accomplishes some of what we want here https://dnomadb.github.io/map-tools/drag-a-tile/

Closing as not currently actionable.

**Comment by dnomadb** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/5084513/206543657-56f19076-38c4-4513-bffc-a3121925cff5.png">
As @mulloverit noted https://dnomadb.github.io/map-tools/drag-a-tile/ mainly works for this:
- Drag a single uncompressed tile, it xray-styles it
- Drag a style, it will (mainly) apply it
