### ISSUE TITLE
Rename this tool

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#63]

**Comment by almccon** [comment]
Oh, I also just noticed that GeoFabrik has a tool also named "Map Compare" https://tools.geofabrik.de/mc/

And here are some others that are also similarly named: https://googlemapsmania.blogspot.com/2014/06/map-comparison-tools.html 

We also had an earlier tool similar to this one that we called "side-by-side" which is also a fairly common name for this concept, such as: https://maps.nls.uk/geo/explore/side-by-side and https://www.dtest.hss.ed.ac.uk/maps/sbs3/ and https://www.esri.com/about/newsroom/arcwatch/compare-two-web-maps-side-by-side/

**Comment by almccon** [comment]
In our [Ranked Choice Voting](https://www.opavote.com/results/6157896472592384) poll, "Maperture" was the clear winner. I made the change in the README, but we will also probably want to change the repo name and the tool name? But of course, this may break things. :)
