### ISSUE TITLE
Handle pixel ratio in responsive mode

### ISSUE THREAD

**Issue by aparlato** [stamen/maperture#69]
See https://github.com/stamen/map-compare/pull/68#pullrequestreview-978594849

As a followup to allowing a responsive size mode: we should see if we can add a control for pixel ratio on the simulated device. Per comment ☝️  we can do this globally with `window.devicePixelRatio`. Let's see if there's a good way to do it just for our map view.

**Comment by mulloverit** [comment]
Closing until comes up again.
