### ISSUE TITLE
Google Map falls out of sync on drag

### ISSUE THREAD

**Issue by aparlato** [stamen/maperture#77]
When using a Google map side by side with a Mapbox map, it appears to get out of sync if you drag the map from the Google side. Dragging from the Mapbox side works as expected so long as you haven't triggered this error yet.

To reproduce:
- Set one map to a Mapbox map and your other map to a Google map
- Drag the Google map
- See `failed to invert matrix` error
- Try dragging the Mapbox side
- See same error continue on drag

![image](https://user-images.githubusercontent.com/15698320/172490589-474a547d-8f50-4541-a16c-c860b5b15666.png)

![Kapture 2022-06-07 at 18 00 08](https://user-images.githubusercontent.com/15698320/172490264-817a94c1-2143-41e3-a9c2-93c17c825d11.gif)

**Comment by aparlato** [comment]
Unfortunately it appears not. I just tried it out, but am still seeing this bug on the `fix-hash-write` branch as well as `main`

**Comment by ebrelsford** [comment]
Alright thanks for checking. I'm having a hard time consistently reproducing it.

**Comment by aparlato** [comment]
Context on closing this: This turned out to be an issue in the local config of a consumer of this app that created a bad hash that was being used when I was testing outside of that use case.
