### ISSUE TITLE
Dropdowns overflow when long options are present

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#79]
For example:

![image](https://user-images.githubusercontent.com/375002/172677536-0bc10efc-20f8-4cc1-8f31-d0b6b702e42a.png)

We should keep dropdowns from overflowing their container.

**Comment by mulloverit** [comment]
Visual bug that doesn't look great if you have long labels in the dropdown options (container doesn't grow and options text doesn't get cut off). 

**Acceptance criteria**
When user uses dropdown either text gets cut off or modal grows.
