### ISSUE TITLE
Selecting a style from branchPatterns does not correctly set the id

### ISSUE THREAD

**Issue by ebrelsford** [stamen/maperture#86]
(Following up on #85.)

## The issue

This appears to only showing up when styles do not have the same `name` field as the `{style}` portion of the url in `branchPatterns`.

We define an `id` field in the dropdown options

https://github.com/stamen/maperture/blob/33d0ed7225a9772e8196d691b1a7de04a1760b56/src/components/MapStyleInput.svelte#L206-L226

And that `id` is the style name from the `branchPatterns` config. But we don't actually use this `id` later as it isn't included in `selected`

https://github.com/stamen/maperture/blob/33d0ed7225a9772e8196d691b1a7de04a1760b56/src/components/MapStyleInput.svelte#L124-L128

...so we always fall back to the `name` field.

## Possible solutions

As a quick test of this, I tried adding an `id` state field for the `MapStyleInput` component and set it (`id = val.id`) in `handleSelect` here

https://github.com/stamen/maperture/blob/33d0ed7225a9772e8196d691b1a7de04a1760b56/src/components/MapStyleInput.svelte#L180-L187

One downside here is I don't believe the `id` gets set on the initial load so we'd have to handle that. I think we should find a fix that fixes this short-term but consider a refactor to make this component easier to follow.

**Comment by ebrelsford** [comment]
CC @aparlato ^ this is my diagnosis, curious to hear your thoughts.

**Comment by aparlato** [comment]
Yep! This sounds the same as the conclusion as #85 ! I had closed #85 after testing locally incorrectly which led me to conclude I was off base.

**Comment by aparlato** [comment]
Reop
