### ISSUE TITLE
Once a local style is viewed, you can't view a style on a branch

### ISSUE THREAD

**Issue by kateler** [stamen/maperture#88]
Steps to reproduce: 
- Run `yarn serve-compare` to launch a local Maperture
- In the left side of the map, choose "Local Light Reference" from the drop-down (that will work)
- In the left side of the map, choose "Light on..." from the drop-down
  - The field to enter the branch name will appear briefly, then disappear and the map will revert to Local Light Reference.

**Comment by aparlato** [comment]
@kateler I suspect this is related to or the same bug as https://github.com/stamen/maperture/issues/86 but I will make sure that the solution there addresses this as well.

**Comment by kateler** [comment]
This is still happening for me, with the same repro steps. Was it fixed when you tried it? 

If it's relevant, I'm using the AWS flavor of Maperture.
