### ISSUE TITLE
Typing in branch name doesn't work sometimes

### ISSUE THREAD

**Issue by kelsey-taylor** [stamen/maperture#89]
## Describe the issue

Trying to use the `xx style on...` with a branch other than the default doesn't always work - sometimes (I'd say it seems like more often than not) the current branch name repopulates the `branch` field as you're typing in a new branch name. It seems to happen more when using the viewer locally.

https://user-images.githubusercontent.com/57634568/182175915-8c5b9983-5644-46ce-95cc-2add08eac534.mov

**Comment by ebrelsford** [comment]
@aparlato Is there any chance there's something happening with polling here?

**Comment by aparlato** [comment]
Looking into this now as part of the refactor in https://github.com/stamen/maperture/issues/86.

Pretty sure this also has to do with `setSelected` being called when we don't want it to and running [this line](https://github.com/stamen/maperture/blob/main/src/components/MapStyleInput.svelte#L252).
