### ISSUE TITLE
Rethink reactive blocks and objects

### ISSUE THREAD

**Issue by aparlato** [stamen/maperture#92]
Discovered this issue in a fork of maperture:

From what I'm reading, it sounds like Svelte [will react on a reactive block to _changes in the value_ of a primitive variable, but for complex objects, will always run on _resetting the value even without known changes_ since it may have mutated](https://stackoverflow.com/questions/61730267/reactive-statements-triggered-too-often).

This is causing some of our reactive blocks to run much more frequently than they should.

As an example, we reset settings very frequently on all map movements, but then we [pass down settings.maps from `App.svelte` as our maps object to children](https://github.com/stamen/maperture/blob/main/src/App.svelte#L153) which is not expected to change frequently. [Down a couple of components in `MapboxGlMap.svelte`](https://github.com/stamen/maperture/blob/main/src/components/MapboxGlMap.svelte#L25), we pick up changes to this map object and reset variables for `url` and `style`. Because `style` is an object, it follows the behavior pattern mentioned above so every time the variable is reset, regardless of real changes, we try to update the style [here](https://github.com/stamen/maperture/blob/main/src/components/MapboxGlMap.svelte#L43). Mapbox GL diffing of styles has hidden this bug from us since it usually finds no changes and doesn't load from scratch, but occasionally a small style bug will reveal that it's trying to reset every time the map moves.

We should rethink some of our use of reactive blocks in Svelte. We might handle this a few different ways, but so long as we develop a clear pattern, then I think we can consider this resolved. We may even be able to simply move `settings` into a store and get a more nuanced handling of when parts of it update.

cc @ebrelsford

**Comment by ebrelsford** [comment]
Today we talked about @aparlato doing an audit of this to see how it's currently impacting the project. Then we can come up with a strategy for handling these cases (eg, would destructuring the objects and only reacting to the specific properties you need work?) and make any necessary changes to the code.

**Comment by aparlato** [comment]
Here's the audit of reactive blocks. There's only a few instances where we run into the issue of updating more than we should, but they could potentially be prone to bugs and would be worth making more explicit.

> Then we can come up with a strategy for handling these cases (eg, would destructuring the objects and only reacting to the specific properties you need work?) and make any necessary changes to the code.

Yea, that makes sense, destructuring is probably the clearest thing we can do if we can narrow in on a single property that will be different since reactive blocks handle primitives well. That said, in an instance like reacting to a change in stylesheet, we may need to just let the reactive block run a lot and rely on a conditional (in this case based on a better diff) to prevent unnecessary updates or setting of variables.

### `App.svelte`
- https://github.com/stamen/maperture/blob/main/src/App.svelte#L84 ✅ 
- https://github.com/stamen/maperture/blob/main/src/App.svelte#L110 ✅ 
- https://github.com/stamen/maperture/blob/main/src/App.svelte#L113 ✅ 

These three are more or less fine since they relate to `settings` and `mapState` which we do expect to change on every resetting of the value.

### `GoogleMap.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/GoogleMap.svelte#L25 ❌ 
  - This could reset more than we want it to. If _any_ map changes, it sets a new value for `mapStyle` despite nothing changing for unaffected maps. This should be more specific.
- https://github.com/stamen/maperture/blob/main/src/components/GoogleMap.svelte#L38 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/GoogleMap.svelte#L42 ✅ 
  - Could probably be combined with the one at L38, but otherwise fine
- https://github.com/stamen/maperture/blob/main/src/components/GoogleMap.svelte#L45-L56 ✅ 

### `Map.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/Map.svelte#L13-L20 ❌ 
  - This fires too frequently, resetting any time _any_ map changes
 
### `MapboxGlMap.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/MapboxGlMap.svelte#L25 ❌ 
  - This fires too frequently, resetting any time _any_ map changes
- https://github.com/stamen/maperture/blob/main/src/components/MapboxGlMap.svelte#L37 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/MapboxGlMap.svelte#L41 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/MapboxGlMap.svelte#L43 ❌ 
  - This fires too frequently, resetting any time _any_ map changes. `url` alone would fire when we want since it's a primitive, but we need to maintain the stylesheet aspect for locally hosted styles.
- https://github.com/stamen/maperture/blob/main/src/components/MapboxGlMap.svelte#L46 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/MapboxGlMap.svelte#L49 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/MapboxGlMap.svelte#L52-L64 ✅ 

### `MapControls.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/MapControls.svelte#L28 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/MapControls.svelte#L29 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/MapControls.svelte#L32 ✅ 

### `MapLocationControl.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/MapLocationControl.svelte#L17-L29 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/MapLocationControl.svelte#L32-L35 ✅ 

### `MapLocationDropdown.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/MapLocationDropdown.svelte#L79-L82 ✅ 
https://github.com/stamen/maperture/blob/main/src/components/MapLocationDropdown.svelte#L84-L86 ✅ 

These could both probably be rethought to be more explicit, but they technically work as expected.

### `Maps.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/Maps.svelte#L17-L30 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/Maps.svelte#L32-L38 ✅ 

### `MapsMirrorLayout.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/MapsMirrorLayout.svelte#L10 ❌ 
  - Getting called on map location changes constantly, should only change when number of maps changes
- https://github.com/stamen/maperture/blob/main/src/components/MapsMirrorLayout.svelte#L12 ❌ 
  - Same as above
- https://github.com/stamen/maperture/blob/main/src/components/MapsMirrorLayout.svelte#L14-L26 ❌ 
  - Same as above

### `MapsResponsiveLayout.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/MapsResponsiveLayout.svelte#L24-L28 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/MapsResponsiveLayout.svelte#L30-L36 ❌ 
  - Fires on every map movement

### `MapSwipeLayout.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/MapsSwipeLayout.svelte#L14 ✅ 

### `MapStyleInput.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/MapStyleInput.svelte#L172-L174 ❌ 
  - This isn't what we're looking for in this issue, but we should only run this if there is actually an error
- https://github.com/stamen/maperture/blob/main/src/components/MapStyleInput.svelte#L177-L179 ✅ 

### `ViewModeControl.svelte`
- https://github.com/stamen/maperture/blob/main/src/components/ViewModeControl.svelte#L12 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/ViewModeControl.svelte#L14-L16 ✅ 
- https://github.com/stamen/maperture/blob/main/src/components/ViewModeControl.svelte#L18-L39 ✅

**Comment by ebrelsford** [comment]
Thanks for doing this! Super helpful. Just to confirm I'm understanding:


> https://github.com/stamen/maperture/blob/main/src/components/Map.svelte#L13-L20
>   This fires too frequently, resetting any time any map changes

Would we prefer to pull `mapId` out of `mapStyle` and only set the `mapId` state variable if `mapStyle.mapId` changed? Would that be two reactive blocks, like this?

```js
$: mapIdFromStyle = mapStyle.mapId;
$: mapId = mapIdFromStyle;
```

> https://github.com/stamen/maperture/blob/main/src/components/Map.svelte#L13-L20
>  This fires too frequently, resetting any time any map changes

Similarly here, presumably we should only refer to `type` in the `switch`, so we need to pull it out as its own state variable, right?

**Comment by aparlato** [comment]
@ebrelsford I think you may have copy/pasted the wrong text/link on the first quote block (I'm assuming it's the link in `GoogleMap.svelte`), but regardless, I think your understanding overall is right. Although, now that I'm looking closer at that particular block, that actually doesn't need to change since it's just a reactive declaration and anything that uses the primitive value it gets set to will behave correctly. So it gets set a lot, but it's the same as the solution we're proposing to solve for other instances (pulling a key out).

Also, to be clear, nothing in this audit is a bug yet, but anywhere we use a reactive block that fires more than we intend is an opportunity for a bug.

So as a solution to problematic instances, like you mention in the second example here, we could pull out a relevant key with a primitive value and use that to trigger the reactive block:
**old**:
```js
$: switch (map.type) {
    case 'google':
      MapComponent = GoogleMap;
      break;
    case 'mapbox-gl':
    default:
      MapComponent = MapboxGlMap;
  }
```
**new**:
```js
$: mapType = map.type;

  $: {
    switch (mapType) {
      case 'google':
        MapComponent = GoogleMap;
        break;
      case 'mapbox-gl':
      default:
        MapComponent = MapboxGlMap;
    }
  }
```

As far as I can tell, Svelte isn't terribly opinionated on approach and I'm struggling to find best practices here. I wonder if we should think about adopting a more explicit convention internally to prevent future bugs? This seems to be common. For example, we could always use reactive blocks as either:
- reactive declarations
- function calls with explicit dependencies

This would prevent us from adding code to reactive blocks that accidentally adds more triggers to it.

So for the example above, that would be:
```js
// Reactive declaration pulling out a primitive value from an object
$: mapType = map.type;

// We can see the dependencies that trigger the function explicitly as arguments to the function
// While all other variables and code is hidden from the reactive block in the function
$: getMapComponent(mapType);

const getMapComponent = (mapType) => {
 switch (mapType) {
      case 'google':
        MapComponent = GoogleMap;
        break;
      case 'mapbox-gl':
      default:
        MapComponent = MapboxGlMap;
    }
}
```

**Comment by ebrelsford** [comment]
> I think you may have copy/pasted the wrong text/link on the first quote block

You're right, fixed.

I like your proposal, let's move in that direction. In particular, making the reactive values arguments to a function that you have to use when invoking the function feels a lot more explicit and legible.
