### ISSUE TITLE
Improvements to zoom/lat/long feature

### ISSUE THREAD

**Issue by kateler** [stamen/maperture#93]
These suggestions are for the feature that let you copy or change the zoom/lat/long: 
<img width="126" alt="image" src="https://user-images.githubusercontent.com/764181/188009337-ae6480dd-889d-4e24-8d93-5bba1f6ae5b2.png">

1. If the user clicks anywhere on the larger numbers (`13.25/40.84/-73.922` in the above example), it should copy them to the clipboard. That's a larger click target than the very small "copy" text. 

2. Once the user has clicked "change", all the text in the pop-up window should be selected by default, so the user doesn't have to select or delete it all before pasting in a new value. If the user wants to manually edit part of it instead of pasting, their actions (move cursor to desired place and type) wouldn't be affected. 
<img width="204" alt="image" src="https://user-images.githubusercontent.com/764181/188009710-4e59cb6c-9734-4fc8-b582-14e51ed296ce.png">

**Comment by kateler** [comment]
@ebrelsford and @aparlato - I'd like to add a plea to prioritize this issue. Hopefully it's not a lot of work and would save me hundreds of clicks a day on days when I'm filing a lot of bugs.

**Comment by ebrelsford** [comment]
@kateler These are in `main` now and will be coming to a deploy near you soon.

**Comment by kateler** [comment]
Hooray!

**Comment by kateler** [comment]
@ebrelsford  - When can I expect to see these improvements in client forks of Maperture?

**Comment by aparlato** [comment]
@kateler you should see a PR today! Thanks for your patience here as this moves downsteam!
