### ISSUE TITLE
When three maps are open, stack horizontally rather than vertically

### ISSUE THREAD

**Issue by kateler** [stamen/maperture#94]
From the default view, when the user clicks "Add Map" a third map is added and the maps are stacked vertically: 
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/764181/188011569-bbd0506b-bc9f-4d7e-a19f-1d6e82df16dc.png">

This isn't the most effective use of the space, and the top map in particular is occluded by the control panel. Since most monitors are wider than they are high, it makes more sense to line up three maps horizontally instead, which would make each map closer to a square shape than a narrow rectangle.

**Comment by almccon** [comment]
Agree, and the more portrait-style orientation is closer to mobile device proportions... but then I guess doing the three-panel "phone" view is also an option for that.

**Comment by ebrelsford** [comment]
Seems fair to me, we can take a look at doing this.

**Comment by kateler** [comment]
How can I see this change? When I try adding a map in [Maperture](https://stamen.github.io/maperture), I still see the vertical stacking.

**Comment by ebrelsford** [comment]
This was just deployed to GitHub Pages so you should now see the desired behavior at the link you referenced.

**Comment by aparlato** [comment]
Oh wow, we did this at the exact same time @ebrelsford haha

**Comment by kateler** [comment]
This is so much better, thanks! Is there an automatic procedure to update client-specific forks of Maperture? Or should I file an issue in the relevant repo?

**Comment by aparlato** [comment]
@kateler, @ebrelsford and I are planning to start doing a weekly port of recent changes over to client-specific forks to keep things up to date. Although if something is a blocking bug, we will bring it in asap.

@ebrelsford I don't think we've decided on a specific day yet, but my inclination would be maybe Wed or Thurs to allow time for any back and forth for ports that aren't straightforward. What do you think?

**Comment by ebrelsford** [comment]
@aparlato Let's do Thurs and start today--and let's move further conversation around this to the relevant channels/repos.
